Update ecs-farget.yaml

diff --git a/.github/workflows/ecs-farget.yaml b/.github/workflows/ecs-farget.yaml
--- a/.github/workflows/ecs-farget.yaml
+++ b/.github/workflows/ecs-farget.yaml
@@ -40,18 +40,23 @@ jobs:
       - name: Create New Task Definition JSON
         id: create_task_def
         run: |
-          NEW_TASK_DEF=$(cat current_task_definition.json | jq \
-          --arg IMAGE_URI "${LATEST_IMAGE_URI}" '.taskDefinition |
-          .containerDefinitions[0].image=$IMAGE_URI |
-          del(.revision, .taskDefinitionArn, .status, .requiresAttributes, .compatibilities, .registeredAt, .registeredBy)')
+          # Create a new task definition based on the current one, ensuring to filter out unwanted parameters
+          NEW_TASK_DEF=$(jq --arg IMAGE_URI "${{ env.LATEST_IMAGE_URI }}" \
+            '.taskDefinition | 
+            .containerDefinitions[0].image=$IMAGE_URI |
+            del(.revision, .taskDefinitionArn, .status, .requiresAttributes, .compatibilities, .registeredAt, .registeredBy)' \
+            current_task_definition.json)
           echo "$NEW_TASK_DEF" > new_task_definition.json
-
 
       - name: Register New ECS Task Definition
         id: register_task_def
         run: |
           TASK_DEFINITION_ARN=$(aws ecs register-task-definition --cli-input-json file://new_task_definition.json \
                                 --query "taskDefinition.taskDefinitionArn" --output text)
+          if [ $? -ne 0 ]; then
+            echo "Error: Failed to register new task definition."
+            exit 1
+          fi
           echo "TASK_DEFINITION_ARN=$TASK_DEFINITION_ARN" >> $GITHUB_ENV
 
       - name: Deploy New Task Definition to ECS Service
@@ -61,6 +66,10 @@ jobs:
             --service cc-demo-app-service \
             --force-new-deployment \
             --task-definition ${{ env.TASK_DEFINITION_ARN }}
+          if [ $? -ne 0 ]; then
+            echo "Error: Failed to update ECS service."
+            exit 1
+          fi
 
       - name: Debug Print fetched IMAGE_TAG
         run: echo "Fetched IMAGE_TAG is:${{ env.LATEST_IMAGE_URI }}"
